# Generated by Django 3.1 on 2020-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fifth',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fourth',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='third',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
