# Generated by Django 3.1 on 2020-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200823_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_price', 'product_title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
