# Generated by Django 3.1 on 2020-09-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fifth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fourth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third',
        ),
    ]
