# Generated by Django 3.1 on 2020-09-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200907_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCatalog',
        ),
    ]
