# Generated by Django 3.1 on 2020-09-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
