# Generated by Django 3.1 on 2020-08-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.CharField(blank=True, default=1, max_length=300),
            preserve_default=False,
        ),
    ]
