# Generated by Django 3.1 on 2020-08-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200810_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='born',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='secname',
        ),
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='sirname',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
