# Generated by Django 3.1 on 2020-08-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
