# Generated by Django 3.1 on 2020-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_passwordforgot'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordforgot',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
