# Generated by Django 3.1 on 2020-08-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_passwordforgot_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordforgot',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
