# Generated by Django 3.1 on 2020-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_dostavka',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
