# Generated by Django 3.1 on 2020-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer_dostavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='images',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
