# Generated by Django 3.1 on 2020-09-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200909_1605'),
        ('orders', '0004_auto_20200922_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
        ),
    ]
