# Generated by Django 3.1 on 2020-09-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_profile_orders'),
        ('orders', '0005_auto_20200922_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default=216, on_delete=django.db.models.deletion.CASCADE, to='shop.profile'),
            preserve_default=False,
        ),
    ]
